Nouvelle page de fin [NGC-41]
incubateur-ademe/nosgestesclimat-site-nextjs pull request #156
Opened 2023-10-23 15:12 UTC by bjlaa

https://www.notion.so/accelerateur-transition-ecologique-ademe/Nouvelle-page-de-fin-1b2bc955384a4addab9712e128e35d34

2023-10-24 06:36 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Est-ce que ce serait possible d'ajouter les emojis manquants côté modèle @Clemog ? Pas fan de ces hacks côté front.

(mes excuses si c'est déjà un sujet en cours)

2023-10-24 07:47 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Pas fan non plus ! Effectivement si ça peut-être ajouté, ajoutons :)

2023-10-24 08:24 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Pourquoi tu n'utilises pas notre lib d'emoji (comme pour les graphes de décomposition ?) 
https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/blob/master/public/images/model

2023-10-24 11:16 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
ça ne correspondrait pas aux maquettes si ?

2023-10-24 11:18 UTC, bjlaa commented on src/components/misc/GithubContributionForm.tsx
> +        onChange={(e) => setSujet((e.target as any).value)}
SHAME !

2023-10-24 13:17 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
On en est vraiment là ?

2023-10-24 13:24 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Je vois d'ailleurs que les emojis des catégories dans la page "Profil" ne sont pas ceux qui devraient être 
Avant:
![image](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/55186402/f8e62302-ea13-49b2-beaa-e616c05e4109)

Après:
![image](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/55186402/d6be74bf-848a-4a56-94d4-0c34a49468f4)


Au moins, on a une banque d'émojis custom, autant les utiliser

2023-10-24 15:38 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/_components/GroupItem.tsx
> +import ChevronRight from '../../../../../design-system/icons/ChevronRight'
../../../../../..

2023-10-24 15:40 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin-old/_components/NewsletterForm.tsx
> +import Confirmation from '../../fin/_components/getResultsByEmail/_components/Confirmation'
Ça aurait plus sa place dans @/components non ?

2023-10-24 15:40 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin-old/page.tsx
Pourquoi garder fin-old ?

2023-10-24 15:41 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/CongratulationsText.tsx
> +            Vous avez terminé le test ! <Emoji>👏</Emoji>
Espace insécable avant le !

2023-10-24 15:41 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/CongratulationsText.tsx
> +            Vous avez terminé le test ! <Emoji>👏</Emoji>
(et avant l'émoji aussi ceci dit)

2023-10-24 15:43 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/FeedbackBanner.tsx
> +  const cardClassName = twMerge('border-none bg-grey-100', className)
Pourquoi ce n'est pas directement dans le jsx ?

2023-10-24 15:45 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +        <Image
Possible de mettre un svg inline directement ? (dans son propre composant). Ça permettrait (entre autre) de modifier les couleurs simplement

2023-10-24 16:00 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Yes carrément d'accord pour se mettre d'accord sur une banque d'icônes !

2023-10-24 16:01 UTC, EmileRolley commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/subcategoriesList/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Pas vraiment des emojis mais ça pourrait être utile : https://lucide.dev/icons/

2023-10-24 16:05 UTC, EmileRolley commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/CongratulationsText.tsx
> +            Vous avez terminé le test ! <Emoji>👏</Emoji>
Il serait préférable de seulement traduire le texte d'ailleurs : 

```suggestion
            {t('Vous avez terminé le test\u202f!')}{' '}<Emoji>👏</Emoji>
```

2023-10-24 16:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
On a 3 façon de passer des dottedName :
- action
- dottedName
- actionDottedName

Est-ce qu'on ne se fixerait pas sur une seule graphie ?

J'ai une préférence pour la première (mais je suis aussi coupable d'utiliser les 3) : on ne passe jamais des objets rules mais toujours des dottedNames, donc ça coule de source selon moi que ce soit ça que l'on reçoive (et le type string confirme la chose)

2023-10-24 16:41 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
Nope nope nope nope nope

2023-10-24 16:43 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesChart/CategoriesChart.tsx
> +import CategoryChartItem from './CategoryChartItem'
CategoryChartItem devrait être dans un dossier categoriesChart

2023-10-24 16:48 UTC, florianpanchout commented on src/design-system/utils/Emoji.tsx
> +    <span aria-hidden className={twMerge('inline', className)} {...props}>
Il y a pas un truc comme quoi leur alt doit être vide s'ils sont juste décoratifs ? Je crois me souvenir de ça du RGAA

2023-10-25 06:01 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/_components/GroupItem.tsx
> +import ChevronRight from '../../../../../design-system/icons/ChevronRight'
Auto-import pète des câbles tout seul de temps en temps

2023-10-25 06:02 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin-old/_components/NewsletterForm.tsx
> +import Confirmation from '../../fin/_components/getResultsByEmail/_components/Confirmation'
Bof, le style est vraiment lié à ce formulaire en particulier

2023-10-25 06:04 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin-old/page.tsx
je l'avais retiré, mais je l'ai remis pour essayer de faire l'apprenti sorcier avec l'AB Testing Vercel ✨

2023-10-25 06:05 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/CongratulationsText.tsx
> +            Vous avez terminé le test ! <Emoji>👏</Emoji>
On pourrait pas ajouter un plugin prettier ? La flemme d'assumer cette charge mentale 💁‍♂️

2023-10-25 06:08 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +        <Image
Hmm ça va faire un composant fatos pour un intérêt qui me semble limité non ? 🤔 on ne va pas avoir à manipuler les couleurs de ce svg si souvent que ça si ?

2023-10-25 06:10 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/page.tsx
> +import HowToAct from './_components/howToAct/HowToAct'
Je trouve pas ça ultra intuitif ton orga 🤨

2023-10-25 06:16 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Je suis d'accord que le type string confirme la chose, néanmoins ça oblige à devoir vérifier en passant la souris sur la variable alors que `actionDottedName` est instantanément explicite. Je préfère tout passer sur `actionDottedName`

2023-10-25 06:20 UTC, bjlaa commented on src/design-system/utils/Emoji.tsx
> +    <span aria-hidden className={twMerge('inline', className)} {...props}>
de mémoire les deux fonctionnent mais on peut ajouter le alt pour tes beaux yeux

2023-10-25 06:20 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/page.tsx
> +import HowToAct from './_components/howToAct/HowToAct'
C'est ce sur quoi on s'est mis d'accord au tout début. Chaque composant enfant est dans un dossier du nom du composant parent (et les composants de page dans un dossier _components). Ça permet d'avoir en un coup d'oeil l'organisation de la page. On peut revenir sur cette décision mais il faut être consistant partout

2023-10-25 06:21 UTC, florianpanchout commented on src/design-system/utils/Emoji.tsx
> +    <span aria-hidden className={twMerge('inline', className)} {...props}>
Nope, je te fais confiance la dessus, monsieur expert accessibilité

2023-10-25 06:21 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
c'est soit ça, soit je ne respecte pas les règles des hooks

2023-10-25 06:23 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin-old/_components/NewsletterForm.tsx
> +import Confirmation from '../../fin/_components/getResultsByEmail/_components/Confirmation'
S'il n'est lié qu'a ce formulaire, pourquoi il est dans un autre dossier ?

2023-10-25 06:25 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +        <Image
Suffit que l'on rajoute un mode nuit et il faut deux images. Le composant n'est pas plus fatos que le fichier svg (voir même plus léger si tu l'optimise via Figma). Il a juste l'avantage d'avoir des couleurs dynamiques (et d'éviter une requête http en plus)

2023-10-25 06:29 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
Ou sinon tu passes des composants enfants à Accordion qui ont chacun leur useRule

2023-10-25 06:42 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
Enfin en tout cas c'est ce qui est possible avec l'existant. Après c'est aussi possible de faire évoluer useEngine pour retourner toutes ces informations (mais alors avec la même nomenclature que useRule). 

Je ne suis pas fan de l'idée parce que avoir useRule nous force à penser en composants réutilisables (et donc à ne pas avoir des composants de 1000 lignes qui font tout). Mais si c'est un besoin de ton côté ça me va que l'on modifie useEngine

2023-10-25 06:43 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Et comment fait-on pour les arrays type : relevantAnsweredQuestions ? Ça devient relevantAnsweredQuestionsDottedName ?

2023-10-25 07:31 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin-old/_components/NewsletterForm.tsx
> +import Confirmation from '../../fin/_components/getResultsByEmail/_components/Confirmation'
J'ai annulé !

2023-10-25 07:31 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +        <Image
Okay je regarde ça

2023-10-25 07:32 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/page.tsx
> +import HowToAct from './_components/howToAct/HowToAct'
je crois qu'on s'était mal compris mais ça me va ! j'ai modifié

2023-10-25 07:34 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Tout à fait

2023-10-25 07:35 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/page.tsx
> +import HowToAct from './_components/howToAct/HowToAct'
On peut faire un POINT TECH pour en parler si tu veux

2023-10-25 07:35 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Non j'en sais rien pas évident de réconcilier dottedName, rules, questions, actions et j'en passe des meilleurs

2023-10-25 07:53 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
J'ai revu le composant Accordion

2023-10-25 07:54 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/CategoriesAccordion.tsx
> +  const { getRuleObject } = useTempEngine()
La classe

2023-10-25 09:28 UTC, EmileRolley commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
On ne devrait pas avoir à mettre le type d'une variable dans son nom. En effet, si c'est le nom d'une action, alors `actionName` (ou même `action`) suffit à partir du moment où elle est annotée du type `DottedName` ou `RuleName`. 

Je repose donc ma question : 
![Screenshot from 2023-10-25 11-24-52](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/44124798/ac8f81c9-5027-4191-a23c-d8955de99e1c)

2023-10-25 09:33 UTC, EmileRolley commented on src/components/misc/GithubContributionForm.tsx
> +        onChange={(e) => setSujet((e.target as any).value)}
Est-ce que l'on a envie de commencer à introduire de nouvelle conversion en `any` ?

2023-10-25 11:47 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Perso je sais que si je lis `action`, `question` ou `rule` c'est toujours une string (on ne passe jamais l'objet, toujours que le dottedName). Donc ça me suffit

2023-10-25 12:03 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
Hum, je le vois moins comme ça, typiquement, pour moi `question` c'est l'attribut question de l'objet `rule`, dottedName c'est le nom de la règle (string)

2023-10-25 13:26 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
La en l'état, dans l'ensemble du code en front, `question` est toujours le dottedName d'une règle. On ne manipule jamais d'objet `rule`

2023-10-25 15:10 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +        <Image
Je te laisse jeter un oeil sur le fichier ; j'ai commencé à l'inline mais y'a des paramètres chelous, une image passée en dataURI. Désolé mais ça me parait plus simple de laisser en l'état

2023-10-25 15:12 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/page.tsx
> +import HowToAct from './_components/howToAct/HowToAct'
N'en dis pas plus je suis dispo MAINTENANT pour parler TECH

2023-10-25 15:17 UTC, bjlaa commented on src/components/misc/GithubContributionForm.tsx
> +        onChange={(e) => setSujet((e.target as any).value)}
done, merci !

2023-10-25 15:37 UTC, EmileRolley commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedAction.tsx
> +  actionDottedName,
> Si j'avais simplement action, je ne saurais pas et je devrais passer ma souris sur la variable pour déterminer la nature de cette dernière.

Il suffit de rajouter l'annotation de type comme ça tu as l'info sans avoir besoin de lsp ou autre. 

Le fait d'inclure le type dans le nom d'une variable alourdit de prochains refactos.

2023-10-26 11:40 UTC, florianpanchout commented on src/design-system/utils/BarChart.tsx
> +      transition={{ delay: 0.5, duration: 0.8, ease: 'easeOut' }}
duration: 0.3, delay de 0.5 + 0.1*index

2023-10-30 10:37 UTC, florianpanchout requested changes

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/ClassementMember.tsx
> +import Badge from '../../../../../../design-system/layout/Badge'
Rooooh

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/PointsListItem.tsx
> +import Badge from '../../../../../../design-system/layout/Badge'
ROOOOOH

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/PointsListItem.tsx
>  import PercentageDiff from './PercentageDiff'
PercentageDif devrait être dans un dossier pointListItem non ?

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/HowToAct.tsx
> +      <h2>Comment agir ?</h2>
Espace insécable (fine si possible) avant les signes doubles

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/getResultsByEmail/Confirmation.tsx
> +          <Trans>Votre simulation est sauvegardée !</Trans>{' '}
Same : espace insécable

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/howToAct/RecommendedActions.tsx
> +import RecommendedAction from './RecommendedAction'
Devrait être dans un dossier recommendedActions

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/AccordionItemWithRule.tsx
> +import SubcategoriesList from './SubcategoriesList'
Devrait être dans un dossier accordionItemWithRule

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoriesList.tsx
> +import SubcategoryListItem from './SubcategoryListItem'
Devrait être dans un dossier subcategoriesList

2023-10-30 10:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
On a pas dit que c'était géré côté modèle ça ?

2023-10-30 10:37 UTC, florianpanchout commented on src/design-system/actions/ActionCard.tsx
> +            - {formatValue(roundValue(footprintAvoided), { precision: 0 })}
Ça nous fait encore une nouvelle façon de gérer l'affichage d'un poids de CO2e non ?

2023-10-30 10:37 UTC, florianpanchout commented on src/design-system/layout/accordion/Accordion.tsx
> +import { AccordionItemType } from './AccordionItem'
Devrais être dans un dossier accordion

2023-10-30 10:40 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/ClassementMember.tsx
> +import Badge from '../../../../../../design-system/layout/Badge'
Ah mais okay ! C'est VSCode qui fait n'importe quoi quand je demande de mettre à jour les routes ! (ce sera aussi mon excuse les prochaines fois que je mets un bug en prod)

2023-10-30 10:42 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/PointsListItem.tsx
>  import PercentageDiff from './PercentageDiff'
Rohhhhhhh

2023-10-30 10:42 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/HowToAct.tsx
> +      <h2>Comment agir ?</h2>
Pourquoi ?

2023-10-30 10:43 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/getResultsByEmail/Confirmation.tsx
> +          <Trans>Votre simulation est sauvegardée !</Trans>{' '}
Pourquoi ?

2023-10-30 10:43 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/AccordionItemWithRule.tsx
> +import SubcategoriesList from './SubcategoriesList'
c'est trop !!

2023-10-30 10:45 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/HowToAct.tsx
> +      <h2>Comment agir ?</h2>
Pour éviter que des signes se retrouvent tout seuls à la ligne

2023-10-30 10:45 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Non on n'a pas réussi à se mettre d'accord. Selon moi on ne doit pas utiliser les icônes modèle pour préserver la cohérence à travers le site. On pourra appeler Jérémie en arbitre au besoin.

2023-10-30 10:46 UTC, bjlaa commented on src/design-system/actions/ActionCard.tsx
> +            - {formatValue(roundValue(footprintAvoided), { precision: 0 })}
Je n'ai pas de réponse à ta question..

2023-10-30 10:56 UTC, florianpanchout commented on src/design-system/actions/ActionCard.tsx
> +            - {formatValue(roundValue(footprintAvoided), { precision: 0 })}
Je me note d'investiguer la chose

2023-10-30 10:57 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Mais on utilise les icônes modèle pourtant non ? C'est juste qu'il en manque 2

2023-10-30 11:07 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Ah je me suis mal exprimé, la discussion portait sur le fait d'utiliser les icônes du dossier `/model`. Effectivement, je peux ajouter deux icônes côté dépôt modele, ce serait plus clean

2023-10-30 11:07 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/categoriesAccordion/SubcategoryListItem.tsx
> +const getIcon = (subcategory: string) => {
Je te propose de laisser comme ça pour le moment et de retirer quand les icônes auront été ajoutées

2023-10-30 11:36 UTC, florianpanchout approved these changes

2023-10-30 11:37 UTC, merged