Use `undefined` as an answer for booleans (NGC-214)
incubateur-ademe/nosgestesclimat-site-nextjs pull request #188
Opened 2023-11-03 10:55 UTC by Clemog

2023-11-06 07:14 UTC, florianpanchout requested changes

2023-11-06 07:14 UTC, florianpanchout commented on src/components/form/question/Mosaic.tsx
> +  useEffect(() => {
Je ne comprends pas ce que fait ce hook ?

2023-11-06 07:14 UTC, florianpanchout commented on src/components/form/question/Mosaic.tsx
> +    const { value, setValue } = useRule(mosaicQuestion)
Impossible d'utiliser un hook dans une boucle

2023-11-06 07:14 UTC, florianpanchout commented on src/publicodes-state/hooks/useRule/index.ts
> +  const { questionsOfMosaic, parent, mosaicType } = useMosaic({
Est-ce que l'information fournie par mosaicType ne devrait pas être retournée par type plutôt ?

2023-11-06 09:46 UTC, Clemog commented on src/components/form/question/Mosaic.tsx
> +    const { value, setValue } = useRule(mosaicQuestion)
Yep yep, je l'ai mis la en attendant pour me souvenir de ce que je voulais faire ahah

2023-11-06 09:47 UTC, Clemog commented on src/components/form/question/Mosaic.tsx
> +  useEffect(() => {
Ce n'est pas du tout fonctionnel pardon, j'aurais du commenter le bloc mais c'est en WIP car je voulais justement en discuter de vive voix avec toi, j'ai pas voulu passer trop de temps à implémenter une feature dont on n'a pas discuté

2023-11-06 09:48 UTC, Clemog commented on src/publicodes-state/hooks/useRule/index.ts
> +  const { questionsOfMosaic, parent, mosaicType } = useMosaic({
Carrément oui ! Avoir un type `selectionMosaic` et `numberMosaic`

2023-11-06 09:48 UTC, Clemog commented on src/publicodes-state/hooks/useRule/useValue.ts
> +        ? 'Pas de choix'
Reste de l'app ?

2023-11-13 15:21 UTC, closed without merging

2023-11-13 15:21 UTC, Clemog commented
Je ferme pour traiter séparément questions booléennes et mosiaques sur la dernière version de preprod