Ajoute les pages actions/plus
incubateur-ademe/nosgestesclimat-site-nextjs pull request #24
Opened 2023-09-15 09:20 UTC by bjlaa

2023-09-21 18:24 UTC, florianpanchout requested changes
Quelques retours qui me semblent à la fois suffisamment importants et suffisamment petits pour être traités avant le merge

2023-09-21 18:24 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/actions/plus/[...dottedName]/page.tsx
> +import { NGCRules } from '@/types/model'
Il ne vaudrait pas mieux le rappatrier dans publicodes-state ? Histoire d'aller chercher tous les types publicodes au même endroit

2023-09-21 18:24 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/actions/plus/[...dottedName]/page.tsx
> +  const encodedName = usePathname().replace('/actions/plus/', '')
Tu peux récupérer les [dottedNames via les props de pages](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes)

2023-09-21 18:24 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/actions/plus/[...dottedName]/page.tsx
> +  const { data: rules } = useRules({
Ce serait "plus propre" de récupérer les règles via useTempEngine non ?

2023-09-22 09:31 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/actions/plus/[...dottedName]/page.tsx
> +  const { data: rules } = useRules({
C'est un hook temporaire mais ce code aussi. A terme plus personne ne fait d'opération sur les rules en dehors de publicodes-state

2023-09-22 14:03 UTC, bjlaa commented
@florianpanchout tout bon !

2023-09-22 14:07 UTC, merged