Optimisation test e2e
incubateur-ademe/nosgestesclimat-site-nextjs pull request #254
Opened 2023-11-25 11:10 UTC by florianpanchout

2023-11-26 16:09 UTC, EmileRolley requested changes

2023-11-26 16:09 UTC, EmileRolley commented on src/helpers/getGeolocation.ts
> +    `${process.env.VERCEL_URL === 'development' ? 'https' : 'http'}://${
Ce n'est pas l'inverse pour HTTPS et HTTP ?

2023-11-26 16:09 UTC, EmileRolley commented on .github/workflows/e2e.yaml
> +  install:
Pourquoi remplacer l'attribut `build` du workflow Cypress par ce job ? Je ne sais pas si c'est lié à ça mais les tests des personas ne sont plus trigger : https://cloud.cypress.io/projects/bkkrae/runs/845/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D

2023-11-26 16:09 UTC, EmileRolley commented on .github/workflows/e2e.yaml
> +          ]
Tu te bases sur quoi pour déterminer le nombre de machines à utiliser ?

(Pour info Cypress te précise à la fin de chaque run le nombre le plus opti de machines à utiliser) : 

![image](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/44124798/9d86cce0-5838-4ed1-a9f5-76e48bb0aac4)

2023-11-27 05:03 UTC, bjlaa commented on src/helpers/getGeolocation.ts
> +    `${process.env.VERCEL_URL === 'development' ? 'https' : 'http'}://${
```suggestion
    `${process.env.VERCEL_URL ? 'https' : 'http'}://${
```

2023-11-27 06:29 UTC, florianpanchout commented on .github/workflows/e2e.yaml
> +  install:
J'ai repris [la nomenclature vu ici](https://docs.cypress.io/guides/continuous-integration/github-actions#Install-Job) mais je doute que ça change quelque chose au final. Je regarde pour les personas

2023-11-27 06:39 UTC, florianpanchout commented on src/helpers/getGeolocation.ts
> +    `${process.env.VERCEL_URL === 'development' ? 'https' : 'http'}://${
C'est même encore pire que ça, je ne teste même pas la bonne variable d'env...

2023-11-27 06:59 UTC, florianpanchout commented on .github/workflows/e2e.yaml
> +  install:
C'est fix. J'avais enlevé la génération des personas de ce job (pour le faire en parallèle de l'attente de la preview). Mais bon, ça doit prendre moins d'une seconde...

2023-11-27 07:26 UTC, EmileRolley commented on .github/workflows/e2e.yaml
> +          ]
![image](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/44124798/3444b52e-d8e7-4ac2-b592-a872dcd60385)

2023-11-27 07:29 UTC, EmileRolley commented on .github/workflows/e2e.yaml
> +          ]
Où est-ce que tu as vu qu'on utilise 14 machines ?

> Je me base sur le nombre total de tests (personas compris). Comme ça une machine par test.

Ca ne vaut peut-être pas la peine d'initialiser une machine pour chacun des tests `/pages`

2023-11-27 07:36 UTC, EmileRolley approved these changes
A part le nombre de containers qui me semble pas forcément nécessaire c'est bon pour moi :ok_hand:

2023-11-27 07:44 UTC, merged