fix: complete traductions manquantes (NGC-444)
incubateur-ademe/nosgestesclimat-site-nextjs pull request #304
Opened 2023-12-13 15:18 UTC by Clemog

2023-12-15 11:58 UTC, bjlaa approved these changes

2023-12-19 11:26 UTC, bjlaa requested changes

2023-12-19 11:26 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/profil/_components/Localisation.tsx
> -  title = 'Ma région de simulation',
Y'avait pas une utilisation de cette prop ?

2023-12-19 11:26 UTC, bjlaa commented on src/components/questions/Plats.tsx
> +import { Trans } from 'react-i18next'
Pas le bon composant ! Il faut importer celui qui est dans _components quelque part

2023-12-19 11:32 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/profil/_components/Localisation.tsx
> -  title = 'Ma région de simulation',
Je viens de checker c'est good

2023-12-19 11:41 UTC, Clemog commented on src/components/questions/Plats.tsx
> +import { Trans } from 'react-i18next'
Aie

2023-12-19 11:42 UTC, Clemog commented on src/app/(layout-with-navigation)/(simulation)/profil/_components/Localisation.tsx
> -  title = 'Ma région de simulation',
Je crois pas justement, j'ai repris title directement dans le composant

2023-12-19 11:48 UTC, bjlaa approved these changes

2023-12-19 12:13 UTC, Clemog commented
@bjlaa je vois que la preview fonctionne pas c'est super bizarre.. Pareil en local

2023-12-19 12:22 UTC, bjlaa commented
@Clemog la page simulateur ne charge pas c'est ça ?

2023-12-19 12:23 UTC, bjlaa commented on src/components/translation/trans/TransClient.tsx
> -import { Trans } from 'react-i18next'
il faut annuler cette modif

2023-12-19 12:24 UTC, bjlaa commented on src/components/translation/trans/TransClient.tsx
> -import { Trans } from 'react-i18next'
c'est le seul endroit où on utilise le Trans de la lib justement

2023-12-19 12:24 UTC, Clemog commented on src/components/translation/trans/TransClient.tsx
> -import { Trans } from 'react-i18next'
Punaisee merci !

2023-12-19 12:32 UTC, merged