Fix: use the order of the sum to sort sub categories
incubateur-ademe/nosgestesclimat-site-nextjs pull request #308
Opened 2023-12-14 16:37 UTC by EmileRolley

2023-12-14 17:22 UTC, Clemog approved these changes

2023-12-18 07:18 UTC, florianpanchout requested changes

2023-12-18 07:18 UTC, florianpanchout commented on src/app/documentation/_components/DocumentationLandingCard.tsx
> +import getNamespace from '@/publicodes-state/helpers/getNamespace'
Plutôt utiliser getCategory de useEngine pour les appels externes à publicodes-state

2023-12-18 08:44 UTC, EmileRolley commented on src/app/documentation/_components/DocumentationLandingCard.tsx
> +import getNamespace from '@/publicodes-state/helpers/getNamespace'
Pourquoi il y a une raison particulière ? Je n'avais pas fais gaffe à la fonction `getCategory`, il y a peut-être des endroits où ce serait plus explicite que `getNamespace` en effet. En revanche, hormis la sémantique qu'elle serait la différence avec utiliser `getNamespace` ?

2023-12-18 08:48 UTC, florianpanchout commented on src/app/documentation/_components/DocumentationLandingCard.tsx
> +import getNamespace from '@/publicodes-state/helpers/getNamespace'
Les seuls "exports" de publicodes-state sont les hooks et les providers. Si on commence à donner accès au reste ça ajoute un niveau de bordel je trouve. La au moins tout est appelé de la même façon et on sait ce qui est "privé" et ce qui est accessible depuis le reste du site.

(Par contre le format de useEngine est peut être à revoir. Mais dans tous les cas, afin de garder un ensemble cohérent, le changement devrait se faire partout et pas juste pour ce helper)

2023-12-18 12:36 UTC, florianpanchout approved these changes

2023-12-19 08:17 UTC, bjlaa commented
On peut merger ça @EmileRolley  ?

2023-12-19 08:18 UTC, bjlaa commented
<img width="692" alt="Capture d’écran 2023-12-19 à 09 18 17" src="https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/assets/12382534/e4861d40-d1c1-475d-8ecb-726fd619092d">

J'ai ma réponse

2023-12-19 10:44 UTC, Clemog commented
> <img alt="Capture d’écran 2023-12-19 à 09 18 17" width="692" src="https://private-user-images.githubusercontent.com/12382534/291521403-e4861d40-d1c1-475d-8ecb-726fd619092d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODI4NzQsIm5iZiI6MTcwMjk4MjU3NCwicGF0aCI6Ii8xMjM4MjUzNC8yOTE1MjE0MDMtZTQ4NjFkNDAtZDFjMS00NzVkLThlY2ItNzI2ZmQ2MTkwOTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMDA1ZmFhMDQ3ZWFhNDI5ZmJhNWRiYTBiNDVkMDVlMWMxNmMyM2RmZWE0ZDVlNDAxMmQ5M2U1MTZlZTViMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQQMidRTmHVAbgEFihruCX7VQ_qJ3xAzGx_d0SX_OwA">
> J'ai ma réponse

C'est déjà merger, on peut publier sur preprod je pense non @EmileRolley ?

2023-12-19 13:03 UTC, Clemog commented
@bjlaa comment on teste en local un test e2e ?
y a pas moyen de récupérer la question courante de manière dynamique plutôt que de fixer la question à laquelle on est sensé être en dur ?

2023-12-19 13:12 UTC, bjlaa commented
@Clemog si c'est possible via la méthode `cy.url().then((url) => fait ce que tu veux )`

2023-12-19 13:13 UTC, bjlaa commented
Je pense que dans le test dont tu as mentionné le lien vers, le but est aussi de vérifier que l'ordre des questions n'a pas changé et reste prédictible, d'où l'écriture en dur

2023-12-19 13:14 UTC, Clemog commented
> @Clemog si c'est possible via la méthode `cy.url().then((url) => fait ce que tu veux )`

Coooool merci !

Pour tester en local, il y a une petite doc qque part ? Genre tester juste un test spécifiquement ?

2023-12-19 13:16 UTC, bjlaa commented
Hmm y'a une commande dans le package.json : `yarn e2e` tu peux l'essayer mais j'ai pris l'habitude de lancer un `npx cypress open` 🤔

2023-12-19 13:44 UTC, merged