Page d’accueil nouveau design (clean) [NGC-154]
incubateur-ademe/nosgestesclimat-site-nextjs pull request #329
Opened 2024-01-08 16:30 UTC by florianpanchout

La même que https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/214 mais sans tous les changements de layout

2024-01-09 14:55 UTC, bjlaa requested changes

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/Contributions.tsx
> +                <span className="text-primary-500 underline">
Il ne faut pas mettre de balises à l'intérieur de `Trans`, il faudrait redécouper ta phrase en plusieurs Trans, c'est relou mais c'est comme ça 🤷

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/Amis.tsx
> +        <Trans>
Pareil pas de balises dans Trans

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/Contributions.tsx
> +              <Trans>
ici aussi

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/Contributions.tsx
> +                <span className="text-primary-500 underline">
aussi ici

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/Heading.tsx
> +              En <span className="text-secondary">10 minutes</span>, obtenez une
aussau issi

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/heading/Buttons.tsx
> +          <Trans>Reprendre mon test</Trans>
Il ne manquerait pas le cas de figure `Voir mes résultats` quand la progression est à 100% ?

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
Possible de faire plus cracra ?

2024-01-09 14:55 UTC, bjlaa commented on src/app/_components/mainLayoutProviders/PageViewTracker.tsx
> +      [...searchParams.keys()].length ? '?' + searchParams : ''
Pourquoi faire un spread ici ?

2024-01-09 15:02 UTC, florianpanchout commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
J'attends ta proposition de réécriture

2024-01-09 15:03 UTC, florianpanchout commented on src/app/_components/heading/Buttons.tsx
> +          <Trans>Reprendre mon test</Trans>
Yes, mais on a accès à la progression dans le localstorage que depuis 30 minutes

2024-01-09 15:06 UTC, bjlaa commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
Défi accepté 🤓

2024-01-09 15:10 UTC, bjlaa commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
```suggestion

const timeoutRef = useRef<NodeJS.Timer>(undefined)

  useEffect(() => {
    if (!firstSelected || !secondSelected) {
      return
    }

    if (firstSelected.iconIndex === secondSelected.iconIndex) {
      setValidatedIcons((prevValidatedIcons) => [
        ...prevValidatedIcons,
        firstSelected,
        secondSelected,
      ])
    } else {
      setIsWrong(true)
    }
    timeoutRef?.current = setTimeout(() => {
      setFirstSelected(null)
      setSecondSelected(null)
      setIsWrong(false)
    }, 1000)
  }, [firstSelected, secondSelected])

  useEffect(() => {
    return () => {
      timeoutRef?.current && clearTimeout(timeoutRef.current)
    }
  }, [])
```

2024-01-09 15:13 UTC, florianpanchout commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
Ahahaha. Merci j'avais besoin de rire un peu aujourd'hui 🥲

2024-01-09 17:14 UTC, bjlaa commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
Oh waouw, à ce niveau là est-ce qu'on parle encore de déni ? 🤔 tu ne peux pas supporter la vue de mon code pur et scintillant ✨

2024-01-09 17:14 UTC, bjlaa commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +    if (firstSelected && secondSelected) {
retourne dans tes ténèbres avec ton code efficace mais cavalier, shoo ! shoo !!!

2024-01-17 08:01 UTC, bjlaa requested changes

2024-01-17 08:01 UTC, bjlaa commented on src/components/icons/KawaiiSteak.js
Je valide ce nom

2024-01-17 08:05 UTC, florianpanchout commented on src/app/_components/Organisations.tsx
> +  const [isHover, setIsHover] = useState(false)
Du vide, ce que tu produis de mieux

2024-01-17 08:08 UTC, florianpanchout commented on src/app/_components/heading/icons/DesktopCircles.tsx
> +  const [validatedIcons, setValidatedIcons] = useState<any[]>([])
Oui je voulais pas passer plus de 30 minutes sur le memory avant d'être sur que c'était un truc qu'on gardait

2024-01-17 08:31 UTC, bjlaa approved these changes
Allez va, ne tiens pas compte de mes retours, tu peux fusionner.. 🙄

2024-01-17 08:43 UTC, merged