Fix: Bug les questions non applicables sont quand même affichées (NGC-465)
incubateur-ademe/nosgestesclimat-site-nextjs pull request #342
Opened 2024-01-15 17:37 UTC by Clemog

2024-01-16 06:38 UTC, florianpanchout requested changes

2024-01-16 06:38 UTC, florianpanchout commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +       * Finally, we check if the folded step is disabled by its parent AND if it's not the current question.
Ça ne fonctionne pas. Si on reprend l'exemple de la moto, lorsque l'on revient sur la question pour répondre "Non", on a bien les deux questions d'après qui disparaissent (et la question "Faites vous de la moto" qui reste puisque current).

Mais des que l'on répond ensuite à une autre question la question "Faites vous de la moto" disparait (puisque plus protégée par current)

2024-01-16 16:11 UTC, florianpanchout commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +      const engine = new Engine(rules, {
Y'a le pristineEngine pour ça ! C'est une shallow copy de l'engine sans situation (donc vierge)

2024-01-16 16:13 UTC, Clemog commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +      const engine = new Engine(rules, {
C'est exactement ce qu'il me fallait

2024-01-16 16:13 UTC, Clemog commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +      const engine = new Engine(rules, {
Pristine ne me parlait pas

2024-01-17 06:45 UTC, florianpanchout commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Y'a une raison de garder ça ? Parce que la il manque beaucoup de choses dans tes dépendances (et c'est toujours ça qui crée des bugs 6 mois plus tard)

2024-01-17 06:53 UTC, florianpanchout commented on src/publicodes-state/providers/formProvider/Provider.tsx
> +    rules,
Plus besoin de rules maintenant (ça casse ton build d'avoir une variable non utilisée)

2024-01-17 07:41 UTC, Clemog commented on src/publicodes-state/providers/formProvider/useQuestions.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
J'avoue que j'ai repris le hook au dessus mais effectivement dans ce cas, je ne crois pas que c'est nécessaire

2024-01-17 12:12 UTC, florianpanchout approved these changes
👌

2024-01-17 12:14 UTC, merged