Mettre toutes les logiques de routing dans un hook [NGC-492]
incubateur-ademe/nosgestesclimat-site-nextjs pull request #381
Opened 2024-02-16 06:48 UTC by florianpanchout

@bjlaa je veux bien que tu jettes un oeil au dossier hooks/navigation et que tu me donnes ton avis

2024-02-16 10:55 UTC, florianpanchout commented on src/hooks/navigation/useEndPage.ts
> +        await saveSimulation({ simulation: currentSimulation, user })
Oui je me suis demandé de si c'était pas plus simple d'envoyer l'objet user directement ? (sachant qu'il a maintenant un userID et plus un id)

2024-02-16 10:55 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/simulateur/[root]/page.tsx
> +  const { isGuardInit, isGuardRedirecting } = useSimulateurGuard()
100% made in Panch (enfin je n'ai pas inventé le principe de guard non plus)

2024-02-16 10:55 UTC, florianpanchout commented on src/hooks/navigation/useInfosPage.ts
> + * @returns {getLinkToNextInfosPage} - A function that returns the link to the next infos page
Il sait toujours trouver le mot juste

2024-02-19 07:37 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/infos/codepostal/page.tsx
> +      router.push(getLinkToNextInfosPage({ curPage: 'postalCode' }))
Pas contre, mais ça servirait à quoi ici ? Entre écrire POSTAL_CODE_PAGE_NAME que l'on a importé de constants ou écrire postalCode directement ?

2024-02-19 07:39 UTC, florianpanchout commented on src/hooks/navigation/usePollPages.ts
> +  const linkToPollDashboard = useCallback(
Parce que c'est une fonction. Elle était mal nommée

2024-02-19 07:39 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/infos/codepostal/page.tsx
> +      router.push(getLinkToNextInfosPage({ curPage: 'postalCode' }))
c'est utile en cas de renommage ou pour éviter des erreurs de frappe (wink wink, birthDate, wink wink)

2024-02-19 07:42 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/infos/codepostal/page.tsx
> +      router.push(getLinkToNextInfosPage({ curPage: 'postalCode' }))
Mais la on parle du nom d'une variable. Ce n'est pas un nom qui existe en dehors de la base de code comme une url ou un id. 

Vu que tu as écris birthDate j'imagine que tu aurais appelé la constante BIRTH_DATE_PAGE_NAME ce qui aurait posé le même problème

2024-02-19 07:46 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/infos/codepostal/page.tsx
> +      router.push(getLinkToNextInfosPage({ curPage: 'postalCode' }))
Boaf la flemme de débattre, do as you please man !

2024-02-19 07:49 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/infos/codepostal/page.tsx
> +      router.push(getLinkToNextInfosPage({ curPage: 'postalCode' }))
Bah non en fait. On travaille sur le même projet donc on doit coder de la même façon.

2024-02-19 16:47 UTC, bjlaa commented on src/hooks/navigation/useEndPage.ts
> +        await saveSimulation({ simulation: currentSimulation, user })
Pas fan de l'idée de balancer de la donnée inutile. Je suis plus pour savoir ce qu'on envoie et pourquoi on l'envoie.

2024-02-22 07:30 UTC, florianpanchout commented
Il y a un problème dans l'affichage des stats du mode groupe mais je garde ça pour une autre PR ; celle ci est déjà suffisamment fat

2024-02-23 10:09 UTC, bjlaa requested changes
Very neat and clean deux trois modifs potentielles mais globalement du très beau code solide

2024-02-23 10:09 UTC, bjlaa commented on src/hooks/groups/useRemoveParticipant.ts
> +      updateCurrentSimulation({ group: null })
Pareil, reset le cache ?

2024-02-23 10:09 UTC, bjlaa commented on src/hooks/tracking/useTrackSimulateur.ts
> +      return
Ohooo c'est chaud ça non ?

2024-02-23 10:09 UTC, bjlaa commented on src/publicodes-state/providers/userProvider/filterLocalStorage.tsx
> +    typeof migrationInstructions.valuesToMigrate[ruleName][
Désolé je trouve ça vraiment pas très facile à lire ; contre-propale !! :
```suggestion
    const value =     migrationInstructions.valuesToMigrate[ruleName][nodeValue as string]
    if (typeof value === string && value !== 'oui' && value !== 'non') {
    situation[ruleName] = machin
    } else {
    ...
    typeof migrationInstructions.valuesToMigrate[ruleName][
```

2024-02-23 10:50 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
Ou utiliser un debounce comme pendant le test non ?

2024-02-23 10:52 UTC, florianpanchout commented on package.json
> +  "version": "1.22.19",
No idea. Je suis sur c'est Copi

2024-02-23 10:53 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/groupResults/Classement.tsx
> +                (member: any, index: number) =>
[Wesh ça vient ta PR](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/356/files

2024-02-23 10:54 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/classement/_components/Groups.tsx
> +        title={<Trans>Groupes d'amis</Trans>}
ami·e·s

2024-02-23 10:57 UTC, florianpanchout commented on src/components/iframe/IframeDataShareModal.tsx
> -    delete data?.bilan
Parce qu'avant on avait un objet qui contenait bilan + catégories et on ne voulait vraisemblablement ne pas envoyer bilan. Maintenant on a un objet qui ne contient que les catégories

2024-02-23 10:58 UTC, florianpanchout commented on src/hooks/groups/useDeleteGroup.ts
> +      updateCurrentSimulation({ group: null })
Pas besoin, on navigue donc la query est refetch automatiquement

2024-02-23 11:00 UTC, florianpanchout commented on src/hooks/tracking/useTrackSimulateur.ts
> +      return
Nope parce qu'on check prevProgression donc on ne devrait pouvoir déclencher qu'une seul condition. Mais ça me semble plus clair comme ça

2024-02-23 11:00 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
bouais ça te gêne pas de refresh tout un DOM pour un petit input ? ça me parait plus économe de gérer ça localement

2024-02-23 11:01 UTC, bjlaa commented on package.json
> +  "version": "1.22.19",
Un vrai salaud ce Copil

2024-02-23 11:04 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
Il n'y a pas de petits inputs. Juste des petits développeurs

2024-02-23 11:42 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
sky is the limit right ?

2024-02-23 11:42 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
bon à voir à l'usage si on a des complaintes

2024-02-23 11:43 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/amis/invitation/_components/InvitationForm.tsx
> +        setPrenom={updateName}
mais au moins ajouter un debounce oui

2024-02-26 08:59 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/GroupModePromotionBanner.tsx
> +  const { t } = useTranslation()
Ah oui, ce sont des erreurs dans ce cas !!

2024-02-26 09:00 UTC, bjlaa approved these changes
Juste virer les `useTranslation` et on est goooood

2024-02-26 09:00 UTC, florianpanchout commented
C'est déjà faiiiit

2024-02-26 09:01 UTC, merged