Parcours Orga / Page Classements - Afficher plusieurs orga (invité) [NGC-696]
incubateur-ademe/nosgestesclimat-site-nextjs pull request #447
Opened 2024-03-25 14:36 UTC by florianpanchout

2024-03-25 15:05 UTC, bjlaa requested changes

2024-03-25 15:05 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/classements/_components/Organisations/PollsList.tsx
> +        .flat(),
c'est rare de voir ça côté front 🧐

2024-03-25 15:05 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/infos/commencer/page.tsx
> +    if (currentSimulationRef.current?.polls !== currentSimulation?.polls) {
Ce sera toujours vrai, tu voulais pas plutôt faire :

```suggestion
    if (currentSimulationRef.current?.polls?.length !== currentSimulation?.polls?.length) {
```

2024-03-25 15:42 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/infos/commencer/page.tsx
> +    if (currentSimulationRef.current?.polls !== currentSimulation?.polls) {
Pourquoi ce serait toujours vrai ?

2024-04-01 10:57 UTC, bjlaa commented on src/app/(layout-with-navigation)/(simulation)/infos/commencer/page.tsx
> +    if (currentSimulationRef.current?.polls !== currentSimulation?.polls) {
Parce que deux arrays ne sont jamais égales sauf si tu compares les mêmes refs. Enfin je crois non ?

2024-04-02 08:05 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/infos/commencer/page.tsx
> +    if (currentSimulationRef.current?.polls !== currentSimulation?.polls) {
Yep, my bad. De toute façon ça ne fonctionne pas si la simulation en cours est déjà associée au poll. J'ai modifié

2024-04-03 06:58 UTC, merged