Ajoute les nouvelles couleurs [NGC-577]
incubateur-ademe/nosgestesclimat-site-nextjs pull request #480
Opened 2024-04-05 15:38 UTC by bjlaa

2024-04-09 06:40 UTC, florianpanchout commented on public/manifest.webmanifest
> +  "orientation": "portrait",
😕

2024-04-09 06:42 UTC, florianpanchout commented on src/app/(layout-with-navigation)/(simulation)/fin/_components/results/TotalCard.tsx
> +        <Emoji className="animate-pulse text-5xl md:text-8xl">🌍</Emoji>
wtf. Les animations Tailwind sont des attentions seekers. C'est un contre sens de mettre ça sur un élément qui n'est pas interactif (et même ici qui est purement décoratif)

2024-04-09 06:44 UTC, florianpanchout commented on src/app/_components/Organisations.tsx
> +      <Rainbow
Ce ne serait pas plus simple de le mettre dans Background ?

2024-04-09 06:47 UTC, florianpanchout commented on src/app/globals.css
> +.rainbow {
Pourquoi les couleurs ne suivent pas celles du logo ? Ça aurait plus de sens (et ça ferait peut être un peu moins basique)

2024-04-09 06:54 UTC, florianpanchout requested changes
Le pulse c'est non

2024-04-09 12:21 UTC, bjlaa commented on src/app/_components/Organisations.tsx
> +      <Rainbow
Hmmm si en le passant en children ! Modifié

2024-04-09 12:26 UTC, florianpanchout commented on src/app/_components/Organisations.tsx
> +      <Rainbow
Pourquoi tu veux le passer en children ? Si tu l'intègre directement dans Background avec un booléen en props pour l'afficher ou non ça suffit non ?

2024-04-09 18:51 UTC, bjlaa commented on src/app/globals.css
> +.rainbow {
affaire à suivre..

2024-04-09 18:51 UTC, bjlaa commented on src/app/_components/Organisations.tsx
> +      <Rainbow
Ça me semble relativement similaire 🤔

2024-04-09 18:52 UTC, bjlaa commented on public/manifest.webmanifest
> +  "orientation": "portrait",
Un petit malin avait commit une bévue

2024-04-10 05:23 UTC, florianpanchout commented on src/app/_components/Organisations.tsx
> +      <Rainbow
J'imagine que c'est un comportement que l'on voudra reproduire sur d'autres Background (et qu'il n'y a que Rainbow qui peut s'afficher ici)

2024-04-16 09:24 UTC, merged