Ajout article déménagement
incubateur-ademe/nosgestesclimat-site-nextjs pull request #498
Opened 2024-04-11 13:44 UTC by JuliePouliquen

Au final on ne l'avait pas mis sur le blog, ce qui est très dommage car il est fouillé et fourni !

2024-04-22 06:55 UTC, florianpanchout commented
Vous voulez faire quoi avec cet article ? Le mettre en prod directement ? Ou l'inclure dans la prochaine release ?

2024-04-22 07:11 UTC, bjlaa commented
Je crois pas qu'il y ait une urgence particulière à le sortir mais je laisse Julie confirmer ça

2024-04-22 09:17 UTC, JuliePouliquen commented
Exactement, pas d'urgence, juste pas envie qu'il soit oublié au fond de la cave de NGC.

2024-04-22 15:23 UTC, jeannelf requested changes
- en vrai je trouve que ca va niveau quantité d'images
- on peut peut etre mettre un peu des emojis mais bon
- impact CO2 on peut pas intégrer le vrai iframe ? plutot qu'un screen ? sinon quitte à mettre un screen faudrait limiter la largeur car quand on est sur desktop les images sont enormeees super larges
- j'aurai mis un CTA tout en bas pour rediriger vers le simu

2024-04-22 18:49 UTC, JuliePouliquen commented
@jeannelf en fait on a essayé l'iFrame mais ça faisait péter l'article. Il y a une histoire de variable en conflit que @bjlaa pourra mieux t'expliquer que moi.
Tout à fait pour un CTA.

2024-04-23 09:17 UTC, florianpanchout commented
Il y a déjà un article de blog avec l'iframe ICO2 intégré. Vous pouvez reprendre le code

2024-04-23 09:51 UTC, JuliePouliquen commented
@jeannelf @florianpanchout iFrame et CTA ajoutés !

2024-04-25 10:07 UTC, jeannelf approved these changes

2024-04-25 10:07 UTC, jeannelf commented
parfaiiit

2024-04-25 12:27 UTC, merged