Better local storage migration (NGC-725)
incubateur-ademe/nosgestesclimat-site-nextjs pull request #546
Opened 2024-05-06 13:58 UTC by Clemog

Un peu plus que la carte

2024-05-07 05:43 UTC, florianpanchout commented on src/publicodes-state/providers/userProvider/usePersistentSimulations.ts
> +        return generateSimulation({
tu peux te passer de {} et de return ici ("nitpick" comme qui dirait)

2024-05-07 05:44 UTC, florianpanchout commented on src/publicodes-state/providers/userProvider/index.tsx
> -  useUpdateOldLocalStorage({ storageKey, migrationInstructions })
Il y avait d'autres chose que la migration de la simulation ici (notamment la migration depuis 'ecolab-climat::persisted-simulation::v2')

2024-05-07 05:46 UTC, florianpanchout requested changes
`useUpdateOldLocalStorage` contient d'autres choses que la migration de la situation (gestion de 'ecolab-climat::persisted-simulation::v2', passage de id à userId, etc.)

En fait, vu que la migration de la situation se faisait à cet endroit, je me pose la question de interêt de le déplacer dans usePersistentSimulation

2024-05-07 08:43 UTC, Clemog commented
Bien vu ! J'ai repris ça, je pense que je vais aussi traiter la carte des "tests" de migration du localstorage ici aussi .. On est plutôt sur des tests unitaires non ?

2024-05-21 13:59 UTC, Clemog commented
@bjlaa tu pourras jeter un oeil à mon dernier commit ? J'ai l'impression que ça fonctionne bien, j'ai testé avec une situation erronée
En revanche toujours ce souci avec ts à l'import, on pourrait essayer de regarder ensemble quand t'auras un moment

2024-05-23 08:14 UTC, bjlaa approved these changes

2024-05-29 07:11 UTC, merged